[phases.setup]
nixPkgs = ["python311", "gcc", "stdenv.cc.cc.lib", "swisseph", "sqlite"]
cmds = ["chmod +x start.sh"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[variables]
PYTHONUNBUFFERED = "1"

[start]
cmd = "sh start.sh"
